name: CI

on: [ push, pull_request_target, workflow_dispatch ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Update test coverage
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: ncruces/go-coverage-report@main
  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs: [ test ]
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
